package main;

import AdminPack.Admin_1;
import ClinicPackage.Clinic;
import DoctorPack.DoctorForm;
import PatientForms.CreateAccount;
import PatientForms.LoggedPatient;
import Users.Patient;
import Users.Doctor;
import Users.Admin;
import javax.swing.JOptionPane;

public class LoginForm extends javax.swing.JFrame {

//Data for testing
//        Clinic.AllAdmins.add(new Admin(1221, "mohamed@gmail.com", "mohamed1221", "mohamed", "1stoctobre", "male"));
//        Clinic.AllAdmins.add(new Admin(1222, "andrea@gmail.com", "andrea1221", "andrea", "1april", "male"));
    public LoginForm() {
        initComponents();
//        Clinic.clearAllData(); //This function call is only used for testing, please don't uncomment it
        Clinic.loadEverything();
    }

    public LoginForm(boolean save) {
        //The parameter is merely used to differentiate between the 
        //starting/initiation/initialization of the program and between "going back
        //to the login form". save = true will save. save = false won't save.
        if (save) {
            initComponents();
            Clinic.saveEverything();
        }
        else {
            initComponents();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Doc = new javax.swing.JRadioButton();
        EmailT = new javax.swing.JTextField();
        Pat = new javax.swing.JRadioButton();
        Adm = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        PasswordT = new javax.swing.JPasswordField();
        LoginB = new javax.swing.JButton();
        RegisterB = new javax.swing.JButton();
        Warning = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Clinic Log in");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(jLabel3)
                .addContainerGap(187, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 510, 60));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Email");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 74, 57, -1));

        buttonGroup1.add(Doc);
        Doc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Doc.setText("Doctor");
        Doc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DocActionPerformed(evt);
            }
        });
        jPanel1.add(Doc, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, -1, -1));
        jPanel1.add(EmailT, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 71, 168, -1));

        buttonGroup1.add(Pat);
        Pat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Pat.setText("Patient");
        Pat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatActionPerformed(evt);
            }
        });
        jPanel1.add(Pat, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, -1, -1));

        buttonGroup1.add(Adm);
        Adm.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Adm.setText("Admin");
        Adm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdmActionPerformed(evt);
            }
        });
        jPanel1.add(Adm, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Password");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 109, -1, -1));
        jPanel1.add(PasswordT, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 106, 168, -1));

        LoginB.setBackground(java.awt.Color.green);
        LoginB.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LoginB.setText("Log in");
        LoginB.setEnabled(false);
        LoginB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBActionPerformed(evt);
            }
        });
        jPanel1.add(LoginB, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 202, 87, -1));

        RegisterB.setBackground(java.awt.Color.blue);
        RegisterB.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RegisterB.setForeground(new java.awt.Color(255, 255, 255));
        RegisterB.setText("Register");
        RegisterB.setEnabled(false);
        RegisterB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterBActionPerformed(evt);
            }
        });
        jPanel1.add(RegisterB, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 233, 87, -1));

        Warning.setForeground(new java.awt.Color(255, 0, 0));
        Warning.setText("Please choose a user type!");
        jPanel1.add(Warning, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 168, -1, 27));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 400, 290));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Andre\\Desktop\\Java Project\\ProjectJava\\clinic background.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, -1));

        setSize(new java.awt.Dimension(774, 532));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatActionPerformed
        RegisterB.setEnabled(true);
        LoginB.setEnabled(true);
        Warning.setVisible(false);
    }//GEN-LAST:event_PatActionPerformed

    private void DocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DocActionPerformed
        RegisterB.setEnabled(false);
        LoginB.setEnabled(true);
        Warning.setVisible(false);
    }//GEN-LAST:event_DocActionPerformed

    private void AdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdmActionPerformed
        RegisterB.setEnabled(false);
        LoginB.setEnabled(true);
        Warning.setVisible(false);
    }//GEN-LAST:event_AdmActionPerformed

    private void RegisterBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterBActionPerformed
        CreateAccount temp = new CreateAccount();
        temp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RegisterBActionPerformed

    private void LoginBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBActionPerformed

        if (EmailT.getText().isEmpty() || String.copyValueOf(PasswordT.getPassword()).isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter an email and a password!", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else {
            if (Pat.isSelected()) {
                int loggedAs = Patient.Login(EmailT.getText(), String.copyValueOf(PasswordT.getPassword()));
                if (loggedAs != -1) {
                    Patient account = Clinic.AllPatients.get(loggedAs);
                    LoggedPatient temp = new LoggedPatient(account);
                    temp.setVisible(true);
                    this.dispose();
                }
                else
                    JOptionPane.showMessageDialog(this, "Please re-check your email & password!", "Incorrect login information", JOptionPane.ERROR_MESSAGE);
            }
            else if (Doc.isSelected()) {
                int loggedAs = Doctor.Login(EmailT.getText(), String.copyValueOf(PasswordT.getPassword()));
                if (loggedAs != -1) {
                    Doctor account = Clinic.AllDoctors.get(loggedAs);
                    DoctorForm temp = new DoctorForm(account);
                    temp.setVisible(true);
                    this.dispose();
                }
                else
                    JOptionPane.showMessageDialog(this, "Please re-check your email & password!", "Incorrect login information", JOptionPane.ERROR_MESSAGE);
            }

            else {
                int loggedAs = Admin.Login(EmailT.getText(), String.copyValueOf(PasswordT.getPassword()));
                if (loggedAs != -1) {
                    Admin_1 temp = new Admin_1();
                    temp.setVisible(true);
                    this.dispose();
                }
                else
                    JOptionPane.showMessageDialog(this, "Please re-check your email & password!", "Incorrect login information", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_LoginBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Adm;
    private javax.swing.JRadioButton Doc;
    private javax.swing.JTextField EmailT;
    private javax.swing.JButton LoginB;
    private javax.swing.JPasswordField PasswordT;
    private javax.swing.JRadioButton Pat;
    private javax.swing.JButton RegisterB;
    private javax.swing.JLabel Warning;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
