package PatientForms;

import main.LoginForm;
import javax.swing.JOptionPane;
import Users.Patient;
import ClinicPackage.Clinic;

public class CreateAccount extends javax.swing.JFrame {

    public CreateAccount() {
        initComponents();
        for (int x = 2022; x >= 1900; x--)
            YY.addItem(x + "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Email = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Password = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        CPassword = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        SaveB = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        gender = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        D = new javax.swing.JComboBox<>();
        M = new javax.swing.JComboBox<>();
        YY = new javax.swing.JComboBox<>();
        date = new javax.swing.JLabel();
        CancelB = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Patient");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 40));

        jPanel2.setPreferredSize(new java.awt.Dimension(480, 380));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Create Account");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 18, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Email :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 70, -1, -1));
        jPanel2.add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 67, 166, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Password :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 110, -1, -1));
        jPanel2.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 107, 166, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Confirm Password :");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 150, -1, -1));
        jPanel2.add(CPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 147, 166, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Name:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 190, -1, -1));
        jPanel2.add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 187, 166, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Date of birth:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 230, -1, -1));

        SaveB.setBackground(java.awt.Color.green);
        SaveB.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        SaveB.setText("Save");
        SaveB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBActionPerformed(evt);
            }
        });
        jPanel2.add(SaveB, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 304, 67, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Gender:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 270, -1, -1));

        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        jPanel2.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 267, 102, -1));

        D.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "D" }));
        D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DActionPerformed(evt);
            }
        });
        jPanel3.add(D);

        M.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        M.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MActionPerformed(evt);
            }
        });
        jPanel3.add(M);

        YY.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "YY" }));
        YY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YYActionPerformed(evt);
            }
        });
        jPanel3.add(YY);

        date.setText("D/M/YY");
        jPanel3.add(date);

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 230, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, 350));

        CancelB.setBackground(java.awt.Color.red);
        CancelB.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CancelB.setText("Cancel");
        CancelB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelBActionPerformed(evt);
            }
        });
        getContentPane().add(CancelB, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Andre\\Desktop\\Java Project\\ProjectJava\\clinic background.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 495));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SaveBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBActionPerformed
        if (Email.getText().isEmpty() || String.copyValueOf(Password.getPassword()).isEmpty() || Name.getText().isEmpty() || ((String) gender.getSelectedItem()).isEmpty())
            JOptionPane.showMessageDialog(this, "Please fill all the fields!", "Empty fields found", JOptionPane.ERROR_MESSAGE);
        else {
            if (Patient.isTaken(Email.getText()))
                JOptionPane.showMessageDialog(this, "Please enter another email!", "Email is taken", JOptionPane.ERROR_MESSAGE);
            else {
                if (!(String.copyValueOf(Password.getPassword()).equals(String.copyValueOf(CPassword.getPassword())))) {
                    JOptionPane.showMessageDialog(this, "Please re-confirm your password!", "Passwords don't match", JOptionPane.ERROR_MESSAGE);
                    CPassword.removeAll();
                }
                else {
                    boolean isEmail = false;
                    for (int x = 0; x < Email.getText().length(); x++) {
                        if (Email.getText().charAt(x) == '@')
                            isEmail = true;
                    }
                    if (!isEmail) {
                        JOptionPane.showMessageDialog(this, "Please enter a valid email!", "Missing @", JOptionPane.ERROR_MESSAGE);
                    }
                    else {
                        if (D.getSelectedIndex() == 0 || M.getSelectedIndex() == 0 || YY.getSelectedIndex() == 0)
                            JOptionPane.showMessageDialog(this, "Please enter your date of birth!", "Missing Date of birth", JOptionPane.ERROR_MESSAGE);
                        else {
                            String DOB = (String) D.getSelectedItem() + '/' + (String) M.getSelectedItem() + '/' + (String) YY.getSelectedItem();
                            Clinic.AllPatients.add(new Patient(Email.getText(), String.copyValueOf(Password.getPassword()), Name.getText(), DOB, (String) gender.getSelectedItem()));
                            JOptionPane.showMessageDialog(this, "Account created successfully!", "Success", JOptionPane.PLAIN_MESSAGE);
                            LoginForm temp = new LoginForm(true);
                            temp.setVisible(true);
                            this.dispose();
                        }
                    }
                }
            }
        }

    }//GEN-LAST:event_SaveBActionPerformed

    private void CancelBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelBActionPerformed
        LoginForm temp = new LoginForm(false);
        temp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CancelBActionPerformed

    private void DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DActionPerformed
        date.setText((String) D.getSelectedItem() + '/' + (String) M.getSelectedItem() + '/' + (String) YY.getSelectedItem());
    }//GEN-LAST:event_DActionPerformed

    private void MActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MActionPerformed
        if (((String) M.getSelectedItem()).equals("M")) {
            D.removeAllItems();
            D.addItem("D");
        }
        else if (M.getSelectedIndex() + 1 == 1 || M.getSelectedIndex() + 1 == 3
                || M.getSelectedIndex() + 1 == 5 || M.getSelectedIndex() + 1 == 7
                || M.getSelectedIndex() + 1 == 8 || M.getSelectedIndex() + 1 == 10
                || M.getSelectedIndex() + 1 == 12) {
            D.removeAllItems();
            D.addItem("D");
            for (int x = 1; x <= 31; x++)
                D.addItem(x + "");
        }
        else if (M.getSelectedIndex() + 1 == 4 || M.getSelectedIndex() + 1 == 6
                || M.getSelectedIndex() + 1 == 9 || M.getSelectedIndex() + 1 == 11) {
            D.removeAllItems();
            D.addItem("D");
            for (int x = 1; x <= 30; x++)
                D.addItem(x + "");
        }
        else { //MM.getSelectedIndex() + 1 == 2
            D.removeAllItems();
            D.addItem("D");
            for (int x = 1; x <= 29; x++)
                D.addItem(x + "");
        }
        date.setText((String) D.getSelectedItem() + "/" + (String) M.getSelectedItem() + "/" + (String) YY.getSelectedItem());
    }//GEN-LAST:event_MActionPerformed

    private void YYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YYActionPerformed
        date.setText((String) D.getSelectedItem() + "/" + (String) M.getSelectedItem() + "/" + (String) YY.getSelectedItem());
    }//GEN-LAST:event_YYActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        }
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        }
        catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        }
        catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        }
        catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField CPassword;
    private javax.swing.JButton CancelB;
    private javax.swing.JComboBox<String> D;
    private javax.swing.JTextField Email;
    private javax.swing.JComboBox<String> M;
    private javax.swing.JTextField Name;
    private javax.swing.JPasswordField Password;
    private javax.swing.JButton SaveB;
    private javax.swing.JComboBox<String> YY;
    private javax.swing.JLabel date;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
