package PatientForms;

import main.LoginForm;
import Users.Patient;
import Users.Doctor;
import ClinicPackage.Slot;
import ClinicPackage.Clinic;
import javax.swing.JOptionPane;

public class LoggedPatient extends javax.swing.JFrame {

    public LoggedPatient() {
        initComponents();
    }

    public LoggedPatient(Patient account) {
        initComponents();
        this.account = account;
        Information1.setVisible(false);
        Information2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        BrowseBooked = new javax.swing.JButton();
        BookApp = new javax.swing.JButton();
        Information1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        Information2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Update = new javax.swing.JButton();
        Logout = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(400, 290));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Please select :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 13, 92, -1));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BrowseBooked.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BrowseBooked.setText("My Appointmens");
        BrowseBooked.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BrowseBookedMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BrowseBookedMouseExited(evt);
            }
        });
        BrowseBooked.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrowseBookedActionPerformed(evt);
            }
        });
        jPanel3.add(BrowseBooked, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, 30));

        BookApp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BookApp.setText("Book an Appointment");
        BookApp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BookAppMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BookAppMouseExited(evt);
            }
        });
        BookApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookAppActionPerformed(evt);
            }
        });
        jPanel3.add(BookApp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Browse & book appointments");

        javax.swing.GroupLayout Information1Layout = new javax.swing.GroupLayout(Information1);
        Information1.setLayout(Information1Layout);
        Information1Layout.setHorizontalGroup(
            Information1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Information1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Information1Layout.setVerticalGroup(
            Information1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Information1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        jPanel3.add(Information1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 210, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Browse, update, and cancel booked");
        Information2.add(jLabel5);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("appointments");
        Information2.add(jLabel4);

        jPanel3.add(Information2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 230, 50));

        Update.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Update.setText("Update Account");
        Update.setFocusPainted(false);
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        jPanel3.add(Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 400, 220));

        Logout.setBackground(new java.awt.Color(255, 0, 0));
        Logout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Logout.setForeground(new java.awt.Color(255, 255, 255));
        Logout.setText("Logout");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        jPanel1.add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 286, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, -1, 340));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Patient");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel2))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Andre\\Desktop\\Java Project\\ProjectJava\\clinic background.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 495));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        LoginForm temp = new LoginForm(true);
        temp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LogoutActionPerformed

    private void BookAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookAppActionPerformed
        if (Clinic.AllDoctors.isEmpty() == false) {
            boolean slotIsAvailable = false;
            for (Doctor doc : Clinic.AllDoctors) {
                for (Slot s : doc.getAssignedSlots()) {
                    if (s != null)
                        if (s.getAvailability() == true) {
                            slotIsAvailable = true;
                            break;
                        }
                }
                if (slotIsAvailable == true)
                    break;
            }
            if (slotIsAvailable == true) {
                BookAppointment temp = new BookAppointment(account);
                temp.setVisible(true);
                this.dispose();
            }
            else
                JOptionPane.showMessageDialog(this, "There are no slots available!", "Notice", JOptionPane.INFORMATION_MESSAGE);
        }
        else
            JOptionPane.showMessageDialog(this, "There are no doctors available", "Notice", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_BookAppActionPerformed

    private void BrowseBookedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrowseBookedActionPerformed
        if (account.getReservations().isEmpty())
            JOptionPane.showMessageDialog(this, "You have not booked any appointments!", "No appointments", JOptionPane.INFORMATION_MESSAGE);
        else {
            BrowseAppointment temp = new BrowseAppointment(account);
            temp.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_BrowseBookedActionPerformed

    private void BrowseBookedMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BrowseBookedMouseEntered
        Information2.setVisible(true);
    }//GEN-LAST:event_BrowseBookedMouseEntered

    private void BrowseBookedMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BrowseBookedMouseExited
        Information2.setVisible(false);
    }//GEN-LAST:event_BrowseBookedMouseExited

    private void BookAppMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BookAppMouseEntered
        Information1.setVisible(true);
    }//GEN-LAST:event_BookAppMouseEntered

    private void BookAppMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BookAppMouseExited
        Information1.setVisible(false);
    }//GEN-LAST:event_BookAppMouseExited

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        UpdateAccount temp = new UpdateAccount(account);
        temp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_UpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoggedPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoggedPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoggedPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoggedPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoggedPatient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BookApp;
    private javax.swing.JButton BrowseBooked;
    private javax.swing.JPanel Information1;
    private javax.swing.JPanel Information2;
    private javax.swing.JButton Logout;
    private javax.swing.JButton Update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
    private Patient account;
}
